---
version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l

  all:
    desc: Run all tasks
    cmds:
      - task install-dev
      - task test
      - task type-check
      - task lint
      - task markdownlint

  test:
    desc: Run tests with pytest
    cmds:
      - uv run pytest --cov=custom_components tests --cov-report=xml

  install-dev:
    desc: Install development dependencies
    cmds:
      - uv venv
      - uv pip install -r requirements-dev.txt

  install:
    desc: Install dependencies
    cmds:
      - uv venv
      - uv pip install -r requirements.txt

  type-check:
    desc: Type check with mypy
    cmds:
      - uv run mypy --config-file=pyproject.toml custom_components

  lint:
    desc: Lint with flake8
    cmds:
      - uv run flake8 custom_components tests

  markdownlint:
    desc: Lint with markdownlint
    cmds:
      - markdownlint-cli2 "**/*.md" "!vendor" "!.venv" --fix

  docs-build:
    desc: Build MkDocs documentation
    cmds:
      - uv run mkdocs build --strict

  docs-serve:
    desc: Serve MkDocs documentation locally
    cmds:
      - uv run mkdocs serve --strict --dev-addr=127.0.0.1:8000

  docs-docker-build:
    desc: Build MkDocs documentation in Docker
    cmds:
      - docker run --rm -v "$PWD":/docs -w /docs python:3.11-slim /bin/sh -c "pip install mkdocs && mkdocs build --strict"

  docs-docker-serve:
    desc: Serve MkDocs documentation in Docker
    cmds:
      - docker run --rm -v "$PWD":/docs -w /docs -p 8000:8000 python:3.11-slim /bin/sh -c "pip install mkdocs && mkdocs serve --dev-addr=0.0.0.0:8000"

  ha-start:
    desc: Start Home assistant, run from dev container
    cmds:
      - supervisor_run

  ha-restart:
    desc: Restart Home assistant, run from dev container
    cmds:
      - ha core restart
