name: 'Setup Python Environment'
description: 'Checks out code, sets up Python, Task, uv, and installs dev dependencies'

inputs:
  python-version:
    description: 'Python version to set up'
    required: false
    default: '3.13'
  dev-dependencies:
    description: 'Install dev dependencies'
    required: false
    default: 'false'
  dependencies:
    description: 'Install dependencies'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Taskfile
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }} # Use github.token in composite actions

    - name: Install uv
      # Using the specific commit SHA you had, as it might be intentional over a simple vX tag
      uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # From user's ci.yml

    - name: Install Python dependencies
      shell: bash
      run: task install-dev
      if: ${{ inputs.dev-dependencies == 'true' }}

    - name: Install Python dependencies
      shell: bash
      run: task install
      if: ${{ inputs.dependencies == 'true' }}
