name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run markdownlint
              uses: actionshub/markdownlint@v3.1.4
            - uses: home-assistant/actions/hassfest@1.0.0
            - name: HACS Action
              uses: hacs/action@22.5.0
              with:
                  category: integration